### ISSUE TITLE
Update text on "Help us improve" dialogue

### ISSUE THREAD

**Issue by 314159265359879** [leather-wallet/desktop#1246]
This is displayed after accepting the terms of the desktop wallet. It has a reference to "Hiro Wallet" that should be replaced with "Leather". 

![image](https://github.com/leather-wallet/desktop/assets/33360391/de94b973-c1e4-4724-b92f-39abab9da371)

**Comment by markmhendrickson** [comment]
I believe this was addressed by https://github.com/leather-wallet/desktop/issues/1234 ?
