### ISSUE TITLE
[4.14.3] Bug: STX staking transaction on Leather pending for 3 hours

### ISSUE THREAD

**Issue by maxsong123** [leather-wallet/desktop#1255]
STX staking transaction pending for 3 hours

I have sent this transaction 3 hours ago and still have not been incorporated into any blocks. 
Thoughts? 

https://explorer.hiro.so/txid/0x5e3b063d9ea8690b92c8197403fa8ab49cb8b7e66e7c7407cc740109c5ee8008?utm_source=leather-wallet&chain=mainnet

**Comment by markmhendrickson** [comment]
It appears confirmed now. lt's possible there was congestion and the fees weren't competitive at the time.
