### ISSUE TITLE
SCR20 Kitty not showing in leather wallet 

### ISSUE THREAD

**Issue by Awais78666** [leather-wallet/desktop#1256]
I have minted kitty SCR20 over 6 months now and they do not show in my wallet can some one please help my wallet address is bc1qfasv3dr8d4u6jt6uz4wgnqyzq32vtzrac3ump2

**Comment by 314159265359879** [comment]
@Awais78666 SRC20 are not displayed in the wallet directly. But you can use the Leather extension to sign in on openstamp.io and stampscan.xyz sign in and check the balances of your account as well as do some actions like send.
