### ISSUE TITLE
[4.14.3] Bug: To carry out a swap between STACKS and token ALEX, I can’nt increase the fees. When I try to do, I have always this message :<describe issue>

### ISSUE THREAD

**Issue by choum45** [leather-wallet/desktop#1257]
Bug found testing Leather build undefined, 4.14.3.

**Comment by choum45** [comment]
To carry out a swap between STACKS and token ALEX, I can’nt increase the fees. When I try to do, I have always this message : 
Your transaction failed to broadcast because of the error: Cannot read properties of undefined (reading 'forEach')

**Comment by markmhendrickson** [comment]
We're working to add fee configuration to swaps

**Comment by markmhendrickson** [comment]
Are you swapping via the ALEX website or the native wallet swaps feature?
