### ISSUE TITLE
[4.14.3] Bug: <BUG with Seed phrase>

### ISSUE THREAD

**Issue by Catriel26** [leather-wallet/desktop#1258]
Today i was trying to send some STX to another address. 
I realized that i forgot my password, so i Reset my account with my 24 words seed phrase. 
After that, i think the app only create a new account with my 24 seed phrase. 
I only got like 110 stx on my account, but on this new account, i have 0. 
And i cant do anything to recover my real account.
I really need some help over here.
Thanks

Bug found testing Leather build undefined, 4.14.3.

**Comment by markmhendrickson** [comment]
cc @314159265359879
