### ISSUE TITLE
[4.14.3] Bug: 10 months ago staked STX, now cannot access

### ISSUE THREAD

**Issue by APRflyonthewall** [leather-wallet/desktop#1259]
Hey Team,

10 Months ago I added my STX to my Hiro Wallet and staked it from the wallet, very easy :)

Anyway just doing the usual check over my assets and cannot find access to the STX, status of the staking etc. 

These is the wallet address transactions for reference. 

https://explorer.hiro.so/address/SPQDJP1JWRKDXCFP3XA54920VVX7Y3GXFMMY21AA?chain=mainnet

I just updated to the leather wallet obviously, is there something I am missing here? Your help would be greatly appreciated.

Regards
Myles Clark

  Thanks for creating an issue. Please include as much detail as possible,
  including screenshots, operating system, and steps to recreate the problem.

  If you have any questions, ask @kyranjamie or @aulneau on Github, Discord and Twitter.

-->

Bug found testing Leather build undefined, 4.14.3.

**Comment by 314159265359879** [comment]
@APRflyonthewall If you stacked them 10 months ago it was likely with Stacks 2.1. (from March 19th 2023) A bug was identified in the proof of transfer protocol shortly after. And there was a quick patch first, a couple of cycles without rewards before a permanent fix was deployed with Stacks 2.4 and a Proof of Transfer contract version 3, this was on May 30th 2023. To Stack with the new contract would have required sending a new transaction to commit or pool.

**Comment by APRflyonthewall** [comment]
@314159265359879 that's a pain, you aware of the action steps needed? Cheers

**Comment by 314159265359879** [comment]
@APRflyonthewall you can follow the regular flow through the wallet again now if you are stacking on your own. If you are stacking in a pool it is best to check with your pool operator. For example Friedger pool now requires users to delegate to a pooling contract instead of a regular address. Whereas planbetter.org nolonger supports the Desktop wallet (use their own app or lockstacks.com with the Leather extension instead).

**Comment by APRflyonthewall** [comment]
@314159265359879 Appreciate the advice, I'd assume it was pooled as the amouth was approx 25k STX but have no idea who with simply because I trusted the wallet to take care with its features. Are you aware of the pool operators at the time this was all integrated into the wallet?

**Comment by APRflyonthewall** [comment]
FIXED - I simply went into the browser version of the leather wallet which gave me access to the fund and transferred them, back into my desktop wallet (secured by my ledger). Funds are now accessible and all is good.
