### ISSUE TITLE
Restore wrong INJ address in Leap wallet with Private Key

### ISSUE THREAD

**Issue by ml3388** [leather-wallet/desktop#1260]
Hi,
I restore a Leap wallet with private key.  All the token addresses in other chains are restored correctly including ATOM, TIA and others, except INJ.  INJ address is different from the original wallet.  Is there a way to restore the correct INJ wallet?

thanks
Michael

**Comment by ml3388** [comment]
I am using Chrome extension Version 0.9.9

**Comment by markmhendrickson** [comment]
Leap appears to be a Cosmos wallet and we don't support Cosmos assets unfortunately.
