### ISSUE TITLE
[4.14.0] Bug: Stacking: keeps waiting on pool

### ISSUE THREAD

**Issue by rjappels** [leather-wallet/desktop#1262]
Bug found testing Leather build undefined, 4.14.0.

I have delegated my STX to the xverse pool via https://pool.xverse.app/stacking. Once on 24jan 2024 and once again on 29feb 2024. Delegation is confirmed but the status keeps being "waiting on pool" . I did my delegation well before the  start of a new cycle, but when the new cycle started my STX where still not locked. When I did my delegation on the 24jan 2024 I waited more than a month but the result was still: "waiting on pool" . What can I do? My address = SPKQVJZM28WJT70G3AP7B0PA5EG4HJ8NH97JK42B. 

Regards
Roel

**Comment by markmhendrickson** [comment]
cc @314159265359879

**Comment by 314159265359879** [comment]
Dear @rjappels looking at your address on the [explorer](https://explorer.hiro.so/address/SPKQVJZM28WJT70G3AP7B0PA5EG4HJ8NH97JK42B?chain=mainnet) I do see your STX locked now. I do recall seeing some messages from Xverse that they had issues committing STX for their poolers in some of the earlier cycles. You'd have to consult Xverse on which cycles they missed exactly. 

If the Wallet version 4.14.0 isn't showing the updated details please upgrade to the latest version first (4.14.3), please let me know if the issue persists after that.

**Comment by rjappels** [comment]
I staked at planbetter. this seems to work. thx
